"""REST API 响应模型."""

from .api_responses import (
    ProjectListResponse,
    ProjectDetailResponse,
    ProjectOperationResponse,
    GroupListResponse,
    GroupSettingsResponse,
    GroupOperationResponse,
    ItemListResponse,
    ItemDetailResponse,
    ItemOperationResponse,
    TagInfoResponse,
    TagOperationResponse,
    StatsResponse,
    MessageResponse,
)
from .common import PagedData
from .data_types import (
    ProjectRegisterResult,
    ProjectRenameResult,
    ProjectDeleteResult,
    ItemCreateResult,
    ItemUpdateResult,
    ItemDeleteResult,
    ItemTagsManageResult,
    GroupCreateResult,
    GroupUpdateResult,
    GroupDeleteResult,
    TagRegisterResult,
    TagUpdateResult,
    TagDeleteResult,
    TagMergeResult,
    TagDetailInfo,
    TagListData,
    GlobalStatsData,
    ToolStatsData,
    ProjectStatsData,
    DailyStatsData,
    StatsCleanupResult,
    GroupConfigDetail,
    GroupListData,
    HealthCheckData,
    RootInfoData,
)

__all__ = [
    # 响应模型
    "PagedData",
    "ProjectListResponse",
    "ProjectDetailResponse",
    "ProjectOperationResponse",
    "GroupListResponse",
    "GroupSettingsResponse",
    "GroupOperationResponse",
    "ItemListResponse",
    "ItemDetailResponse",
    "ItemOperationResponse",
    "TagInfoResponse",
    "TagOperationResponse",
    "StatsResponse",
    "MessageResponse",
    # 数据类型
    "ProjectRegisterResult",
    "ProjectRenameResult",
    "ProjectDeleteResult",
    "ItemCreateResult",
    "ItemUpdateResult",
    "ItemDeleteResult",
    "ItemTagsManageResult",
    "GroupCreateResult",
    "GroupUpdateResult",
    "GroupDeleteResult",
    "TagRegisterResult",
    "TagUpdateResult",
    "TagDeleteResult",
    "TagMergeResult",
    "TagDetailInfo",
    "TagListData",
    "GlobalStatsData",
    "ToolStatsData",
    "ProjectStatsData",
    "DailyStatsData",
    "StatsCleanupResult",
    "GroupConfigDetail",
    "GroupListData",
    "HealthCheckData",
    "RootInfoData",
]
